### ISSUE TITLE
@solid-codemirror/core does not provide an export named CodeMirrorProps

### ISSUE THREAD

**Issue by milahu** [nimeshnayaju/solid-codemirror#6]
with demo code from readme

https://github.com/nimeshnayaju/solid-codemirror/blob/26a66f510fee998b20bc2a05be1d8435ee32da7b/packages/core/src/createCodeMirror.ts#L9

should be export?

**Comment by nimeshnayaju** [comment]
Hey, thanks for submitting the issue. You should be able to import `CodeMirrorProps` in the following way on your app:

https://github.com/nimeshnayaju/solid-codemirror/blob/main/packages/codemirror/src/CodeMirror.tsx#L4

Let me know if this works!

**Comment by milahu** [comment]
aah, `CodeMirrorProps` are just types

i use javascript
